.PHONY: clean all get_message set_message
all: get_message set_message

get_message:
	(cd get_message; make)

set_message:
	(cd set_message; make)

clean:
	(cd get_message; make clean)
	(cd set_message; make clean)